import {Router} from 'express';import * as auth from '../controllers/auth.controller.js';import * as blog from '../controllers/blog.controller.js';import * as admin from '../controllers/admin.controller.js';import * as ai from '../controllers/ai.controller.js';import {upload,uploadImage} from '../controllers/upload.controller.js';import {asyncHandler} from '../utils/api.js';import {protect,authorize} from '../middlewares/auth.js';
const r=Router();
r.get('/health',(req,res)=>res.json({status:'ok',time:new Date().toISOString()}));
r.post('/auth/register',asyncHandler(auth.register));r.post('/auth/login',asyncHandler(auth.login));r.post('/auth/refresh',asyncHandler(auth.refresh));r.post('/auth/logout',asyncHandler(auth.logout));r.get('/auth/me',protect,asyncHandler(auth.me));r.patch('/auth/profile',protect,asyncHandler(auth.updateProfile));r.patch('/auth/password',protect,asyncHandler(auth.changePassword));r.post('/auth/forgot-password',asyncHandler(auth.forgotPassword));r.post('/auth/verify-otp',asyncHandler(auth.verifyOtp));
r.get('/blogs',asyncHandler(blog.list));r.get('/blogs/suggestions/personalized',protect,asyncHandler(blog.suggestions));r.get('/blogs/:slug',asyncHandler(blog.get));r.post('/blogs',protect,authorize('super_admin','admin','editor','author'),asyncHandler(blog.create));r.patch('/blogs/:id',protect,asyncHandler(blog.update));r.delete('/blogs/:id',protect,authorize('super_admin','admin','editor'),asyncHandler(blog.remove));r.patch('/blogs/:id/restore',protect,authorize('super_admin','admin'),asyncHandler(blog.restore));r.patch('/blogs/bulk/actions',protect,authorize('super_admin','admin','editor'),asyncHandler(blog.bulk));r.post('/blogs/:id/like',protect,asyncHandler(blog.like));r.post('/blogs/:id/bookmark',protect,asyncHandler(blog.bookmark));
r.post('/ai/generate',protect,asyncHandler(ai.aiGenerate));r.post('/ai/moderate',protect,asyncHandler(ai.aiModerate));r.post('/media',protect,upload.single('file'),asyncHandler(uploadImage));
r.get('/admin/overview',protect,authorize('super_admin','admin'),asyncHandler(admin.overview));r.get('/admin/users',protect,authorize('super_admin','admin'),asyncHandler(admin.users));r.post('/admin/users',protect,authorize('super_admin'),asyncHandler(admin.upsertUser));r.patch('/admin/users/:id',protect,authorize('super_admin'),asyncHandler(admin.upsertUser));r.delete('/admin/users/:id',protect,authorize('super_admin'),asyncHandler(admin.deleteUser));
for(const [base,crud] of [['categories',admin.categoryCrud],['tags',admin.tagCrud],['comments',admin.commentCrud]]){r.get(`/admin/${base}`,protect,authorize('super_admin','admin'),asyncHandler(crud.list));r.post(`/admin/${base}`,protect,authorize('super_admin','admin'),asyncHandler(crud.create));r.patch(`/admin/${base}/:id`,protect,authorize('super_admin','admin'),asyncHandler(crud.update));r.delete(`/admin/${base}/:id`,protect,authorize('super_admin','admin'),asyncHandler(crud.remove));}
r.route('/admin/settings').get(protect,authorize('super_admin'),asyncHandler(admin.settings)).post(protect,authorize('super_admin'),asyncHandler(admin.settings));
export default r;
